const CoursesDetails = [{
    id: 0,
    backgroundcolor: "rgb(90 170 179)",
    borderColor: "#ED1847",
    title: "English Junior 1 and Junior 2",
    lessonpack: "/lessonpacks/EnglishGrade1.pdf",
    subject : "English Language",
    grade: "Nursery",
    curriculum: "Learn how to read in 100 easy lessons, tracing 2 letter to 4 letter words and preschool early learning themes. ",
    
},
{
    id: 1,
    backgroundcolor: "rgb(212 179 255)",
    borderColor: "#B41E8E",
    lessonpack: "/lessonpacks/EnglishGrade2.pdf",
    title: "English Junior 3",
    subject : "English Language",
    grade: "KG",
    curriculum: "Vocabulary Building, Sentence Structure, Key Grammar concepts (nouns, pronouns, adjectives, punctuation and more) ",
},
{
    id: 1,
    backgroundcolor: "rgb(140 154 223)",
    borderColor: "#50B848",
    lessonpack: "/lessonpacks/EnglishGrade3.pdf",
    title: "English Senior",
    subject : "English Language",
    grade: "Grade 1",
    curriculum: "Vocabulary Development, Creative writing and Comprehension through imaginative stories.",
},
{
    id: 2,
    backgroundcolor: "rgb(195 116 116)",
    borderColor: "#FFA748",
    lessonpack: "",
    title: "Math K - 7",
    subject : "Mathematics",
    grade: "",
    curriculum: " Practice worksheets on each concept as per school curriculum, quizzes, critical thinking puzzles, tearable activities, mental math calculation skill building",
},
{
    id: 3,
    backgroundcolor: "#FCAA93",
    borderColor: "#00ABBD",
    lessonpack: "",
    title: "Urdu",
    subject : "",
    grade: null,
    curriculum: "Haroof recognition, learning how to build words, inspiring local stories, our culture and much more.",
},
{
    id: 4,
    title: "Coding",
    borderColor: "#FDB913",
    lessonpack: "/lessonpacks/Coding.docx",
    subject : "Computer Studies",
    grade: "",
    backgroundcolor: "rgb(27 179 195)",
    curriculum: "Introduction to Coding, sequencing, loops, animation, parallelism and events, debugging, broadcasts, conditionals and sensing, game design, cloning and more. ",
}
]

export default CoursesDetails;